### ISSUE TITLE
This might be the worst code I've seen in a long time.

### ISSUE THREAD

**Issue by caden1249** [cop-discord/Antinuke-Clone#1]
What the hell is this Cop?

**Comment by wintersdevs** [comment]
i don't care, cry skid cry, fucking loser named caden.

**Comment by caden1249** [comment]
Your only commit is adding a type ignore to a module import error, nice moron

**Comment by caden1249** [comment]
maybe try installing the library in your virtual env dumbass retard rofl

**Comment by wintersdevs** [comment]
skid mad btw & i did already i just felt like adding it cry loser

**Comment by wintersdevs** [comment]
poor nigga crying over a commit is wild & corny

**Comment by caden1249** [comment]
You just felt like adding a type ignore, yeah bro you're a genius programmer

**Comment by wintersdevs** [comment]
cry more loser i got better shit to do than deal with poor skids like you..

**Comment by caden1249** [comment]
![image](https://github.com/cop-discord/Antinuke-Clone/assets/98668230/e70ac41c-e567-4aa5-ac3c-ef1f67b39ad0)
![image](https://github.com/cop-discord/Antinuke-Clone/assets/98668230/287ae029-8bb1-4ab6-bdce-467a4a2cb38c)

Nice commits bro
